2020-04-30 10:59:22,840 [14] ERROR MIUWebAPI.Helper.Logger - Error occurred at controller (Course) and action (GetCourse) - 
2020-04-30 14:17:52,358 [8] ERROR MIUWebAPI.Helper.Logger - Error occurred at controller (Course) and action (GetCourse) - 
2020-04-30 14:25:17,745 [33] ERROR MIUWebAPI.Helper.Logger - Error occurred at controller (Course) and action (GetCourse) - 
2020-04-30 14:25:45,500 [33] ERROR MIUWebAPI.Helper.Logger - Error occurred at controller (Course) and action (GetCourse) - 
2020-04-30 14:25:53,693 [37] ERROR MIUWebAPI.Helper.Logger - Error occurred at controller (Course) and action (GetCourse) - 
2020-04-30 15:32:09,763 [7] ERROR MIUWebAPI.Helper.Logger - Error occurred at controller (Course) and action (GetCourse) - 
2020-04-30 15:36:26,996 [6] ERROR MIUWebAPI.Helper.Logger - Error occurred at controller (Course) and action (GetCourse) - 
