//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIUWebAPI.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessorCommentDetail
    {
        public int ID { get; set; }
        public int AssessorCommentID { get; set; }
        public Nullable<int> AssignmentCriteriaID { get; set; }
        public string CustomMessage { get; set; }
        public string CustomMessage2 { get; set; }
        public string CustomMessage3 { get; set; }
        public Nullable<bool> Marked { get; set; }
        public string AssignmentCriteriaDetailIDs { get; set; }
    
        public virtual AccessorComment AccessorComment { get; set; }
    }
}
