//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIUWebAPI.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessorComment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccessorComment()
        {
            this.AccessorCommentDetails = new HashSet<AccessorCommentDetail>();
        }
    
        public int ID { get; set; }
        public int AssignmentSubmissionID { get; set; }
        public Nullable<int> GradingSystem { get; set; }
        public Nullable<int> GradingOverall { get; set; }
        public string AssessorFeedback { get; set; }
        public string ActionPlan { get; set; }
        public Nullable<int> Stage { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> AccessorID { get; set; }
        public Nullable<int> Attitude { get; set; }
        public Nullable<int> Skill { get; set; }
        public Nullable<int> Knowledge { get; set; }
    
        public virtual AssignmentSubmission AssignmentSubmission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccessorCommentDetail> AccessorCommentDetails { get; set; }
        public virtual User User { get; set; }
    }
}
