//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIUWebAPI.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignmentCriteriaDetail
    {
        public int ID { get; set; }
        public Nullable<int> AssignmentCriteriaID { get; set; }
        public string Description { get; set; }
        public Nullable<int> OrderID { get; set; }
        public string Negative { get; set; }
        public string Positive { get; set; }
    
        public virtual AssignmentCriteria AssignmentCriteria { get; set; }
    }
}
