//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIUWebAPI.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignmentSubmissionDetail
    {
        public int ID { get; set; }
        public Nullable<int> AssignmentSubmissionID { get; set; }
        public string FileName { get; set; }
        public string IsMain { get; set; }
        public string IsNewPDF { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual AssignmentSubmission AssignmentSubmission { get; set; }
    }
}
