//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIUWebAPI.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignmentBackupDetail
    {
        public long Id { get; set; }
        public long AssBackupId { get; set; }
        public string FileName { get; set; }
        public string ErrorLog { get; set; }
        public string Status { get; set; }
    
        public virtual AssignmentBackup AssignmentBackup { get; set; }
    }
}
