//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIUWebAPI.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int ID { get; set; }
        public int TermID { get; set; }
        public int StudentID { get; set; }
        public int TermDetailID { get; set; }
        public int TimeTableDetailID { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Week { get; set; }
        public Nullable<bool> IsAttending { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> LectureID { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    
        public virtual Term Term { get; set; }
        public virtual TermDetail TermDetail { get; set; }
        public virtual TimeTableDetail TimeTableDetail { get; set; }
        public virtual User User { get; set; }
    }
}
