//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIUWebAPI.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLog
    {
        public int ID { get; set; }
        public string Action { get; set; }
        public string RelatedTable { get; set; }
        public int RelatedID { get; set; }
        public string Before { get; set; }
        public string After { get; set; }
        public string AdditionalInfo { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string Duration { get; set; }
    }
}
