//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIUWebAPI.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatchDetail
    {
        public int ID { get; set; }
        public int BatchID { get; set; }
        public int StudentID { get; set; }
        public string Remark { get; set; }
        public Nullable<int> AssignmentStatus { get; set; }
        public Nullable<int> OnUserID { get; set; }
        public Nullable<System.DateTime> OnDate { get; set; }
        public Nullable<int> OffUserID { get; set; }
        public Nullable<System.DateTime> OffDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual Batch Batch { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
    }
}
