//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIUWebAPI.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class DownloadHistory
    {
        public int ID { get; set; }
        public Nullable<int> MICResourceFileID { get; set; }
        public Nullable<int> MIUResourceFolderDetailID { get; set; }
        public string UserLoginName { get; set; }
        public Nullable<System.DateTime> CreatedDatetime { get; set; }
    
        public virtual MICResourceFile MICResourceFile { get; set; }
        public virtual MIUResourceFolderDetail MIUResourceFolderDetail { get; set; }
    }
}
