//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIUWebAPI.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailBroadcast
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmailBroadcast()
        {
            this.EmailBroadcastUsers = new HashSet<EmailBroadcastUser>();
        }
    
        public int ID { get; set; }
        public string Recipient { get; set; }
        public Nullable<int> CourseID { get; set; }
        public Nullable<int> BatchID { get; set; }
        public Nullable<int> ProsepctusYear { get; set; }
        public Nullable<int> GraduatedYear { get; set; }
        public Nullable<int> Count { get; set; }
        public string ListName { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailBroadcastUser> EmailBroadcastUsers { get; set; }
    }
}
