//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIUWebAPI.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enquiry
    {
        public int ID { get; set; }
        public string Subject { get; set; }
        public Nullable<int> PostedBy { get; set; }
        public string EnquiryDetails { get; set; }
        public Nullable<System.DateTime> Posted_DateTime { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> Status { get; set; }
        public string ContactName { get; set; }
        public string ContactNumber { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public string ContactEmail { get; set; }
        public string Source { get; set; }
    
        public virtual User User { get; set; }
    }
}
