//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIUWebAPI.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventCalendarReact
    {
        public int ID { get; set; }
        public Nullable<int> EventID { get; set; }
        public string Action { get; set; }
        public string LoginName { get; set; }
        public Nullable<bool> Flag { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedUser { get; set; }
    
        public virtual EventCalendar EventCalendar { get; set; }
    }
}
