//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIUWebAPI.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class FavoriteList
    {
        public int UserID { get; set; }
        public int FavoriteID { get; set; }
        public string FavoriteType { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
