//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIUWebAPI.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedBack
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> TermID { get; set; }
        public Nullable<int> SQfeedback1 { get; set; }
        public string SQSuggestion { get; set; }
        public Nullable<int> ModuleFeedback1 { get; set; }
        public Nullable<int> ModuleFeedback2 { get; set; }
        public Nullable<int> ModuleFeedback3 { get; set; }
        public Nullable<int> ModuleFeedback4 { get; set; }
        public Nullable<int> AEfeedback3 { get; set; }
        public Nullable<int> AEfeedback4 { get; set; }
        public Nullable<int> AEfeedback5 { get; set; }
        public string AESuggestion { get; set; }
        public Nullable<int> FQfeedback1 { get; set; }
        public string FQSuggestion { get; set; }
        public string SuggestionMIC { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDatetime { get; set; }
    
        public virtual Term Term { get; set; }
        public virtual User User { get; set; }
    }
}
