//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIUWebAPI.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstallmentPlanDetail
    {
        public int Id { get; set; }
        public int InstallmentPlanId { get; set; }
        public int FromTermId { get; set; }
        public int ToTermId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public bool IsDiscount { get; set; }
        public decimal DiscountPercent { get; set; }
        public decimal TotalDiscount { get; set; }
        public short Sequence { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual InstallmentPlan InstallmentPlan { get; set; }
    }
}
