//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIUWebAPI.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class IVComment
    {
        public int ID { get; set; }
        public int AssignmentSubmissionID { get; set; }
        public int GradingOverall { get; set; }
        public Nullable<int> CriteriaFlag1 { get; set; }
        public string CriteriaCustomMessage1 { get; set; }
        public Nullable<int> CriteriaFlag2 { get; set; }
        public string CriteriaCustomMessage2 { get; set; }
        public Nullable<int> CriteriaFlag3 { get; set; }
        public string CriteriaCustomMessage3 { get; set; }
        public Nullable<int> CriteriaFlag4 { get; set; }
        public string CriteriaCustomMessage4 { get; set; }
        public Nullable<int> CriteriaFlag5 { get; set; }
        public string CriteriaCustomMessage5 { get; set; }
        public Nullable<int> CriteriaFlag6 { get; set; }
        public string CriteriaCustomMessage6 { get; set; }
        public Nullable<int> CriteriaFlag7 { get; set; }
        public string CriteriaCustomMessage7 { get; set; }
        public int Status { get; set; }
        public int IVID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual AssignmentSubmission AssignmentSubmission { get; set; }
        public virtual User User { get; set; }
    }
}
