//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIUWebAPI.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeadNotification
    {
        public int ID { get; set; }
        public int NotificationId { get; set; }
        public int LeadId { get; set; }
    
        public virtual Notification Notification { get; set; }
        public virtual Lead Lead { get; set; }
    }
}
