//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIUWebAPI.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lead
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lead()
        {
            this.LeadActivities = new HashSet<LeadActivity>();
            this.LeadDocs = new HashSet<LeadDoc>();
            this.LeadNotifications = new HashSet<LeadNotification>();
            this.FamilyMembers = new HashSet<FamilyMember>();
        }
    
        public int ID { get; set; }
        public Nullable<int> LeadOwner { get; set; }
        public string LeadType { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> Probability { get; set; }
        public Nullable<int> ProspectusYear { get; set; }
        public string Mobile { get; set; }
        public string HomePhone { get; set; }
        public string Industry { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string LeadSource { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Country { get; set; }
        public Nullable<int> State { get; set; }
        public string Township { get; set; }
        public Nullable<int> City { get; set; }
        public string Address { get; set; }
        public string Remark { get; set; }
        public string Status { get; set; }
        public string ContactName { get; set; }
        public Nullable<int> CourseID { get; set; }
        public string ContactNumber { get; set; }
        public string Relationship { get; set; }
        public string ContactHomePhone { get; set; }
        public Nullable<int> ConvertedStudentID { get; set; }
        public string ConvertedContactID { get; set; }
        public string DocStatus { get; set; }
        public string PaymentStatus { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedUser { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeadActivity> LeadActivities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeadDoc> LeadDocs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeadNotification> LeadNotifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FamilyMember> FamilyMembers { get; set; }
        public virtual User User { get; set; }
    }
}
