//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIUWebAPI.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class LearningOutcome
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LearningOutcome()
        {
            this.AssignmentCriterias = new HashSet<AssignmentCriteria>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public string NumericFormat { get; set; }
        public string Description { get; set; }
        public Nullable<int> OrderID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssignmentCriteria> AssignmentCriterias { get; set; }
        public virtual Module Module { get; set; }
    }
}
