//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIUWebAPI.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsVisibility
    {
        public long Id { get; set; }
        public long NewsId { get; set; }
        public int VisibilityId { get; set; }
    
        public virtual News News { get; set; }
        public virtual NewsfeedVisibility NewsfeedVisibility { get; set; }
    }
}
