//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIUWebAPI.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsContent
    {
        public long Id { get; set; }
        public long NewsId { get; set; }
        public string TextContent { get; set; }
        public string PhotoPath { get; set; }
        public string DocPath { get; set; }
        public string DocName { get; set; }
        public int Sequence { get; set; }
        public System.DateTime CreatedDatetime { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDatetime { get; set; }
    
        public virtual News News { get; set; }
    }
}
