//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIUWebAPI.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentSettingDetail
    {
        public int ID { get; set; }
        public int PaymentSettingID { get; set; }
        public int TermID { get; set; }
        public string Amount { get; set; }
        public System.DateTime DueDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string Status { get; set; }
    
        public virtual PaymentSetting PaymentSetting { get; set; }
        public virtual Term Term { get; set; }
    }
}
