//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIUWebAPI.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Remodule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Remodule()
        {
            this.RemoduleDetails = new HashSet<RemoduleDetail>();
        }
    
        public int Id { get; set; }
        public int UserID { get; set; }
        public int CourseID { get; set; }
        public int BatchID { get; set; }
        public System.DateTime PaymentDueDate { get; set; }
        public decimal Amount { get; set; }
        public bool Status { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual Course Course { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RemoduleDetail> RemoduleDetails { get; set; }
        public virtual Batch Batch { get; set; }
        public virtual User User { get; set; }
    }
}
