//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIUWebAPI.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultReportIssue
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> BatchId { get; set; }
        public Nullable<int> TermId { get; set; }
        public Nullable<int> TermDetailId { get; set; }
        public Nullable<int> ModuleId { get; set; }
        public string Reason { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual Term Term { get; set; }
        public virtual TermDetail TermDetail { get; set; }
        public virtual Batch Batch { get; set; }
        public virtual Module Module { get; set; }
        public virtual User User { get; set; }
    }
}
