//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIUWebAPI.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemTimeTable
    {
        public int ID { get; set; }
        public string CourseKey { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public string Section { get; set; }
        public int SectionType { get; set; }
    }
}
