//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIUWebAPI.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemModulePermission
    {
        public int Id { get; set; }
        public int SystemModuleId { get; set; }
        public bool CreateEdit { get; set; }
        public bool Delete { get; set; }
        public bool View { get; set; }
        public string RoleId { get; set; }
    
        public virtual AspNetRole AspNetRole { get; set; }
        public virtual SystemSubModule SystemSubModule { get; set; }
    }
}
