//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIUWebAPI.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TemplateDetail()
        {
            this.TemplateDetailSubs = new HashSet<TemplateDetailSub>();
        }
    
        public int ID { get; set; }
        public int TemplateID { get; set; }
        public string TermCode { get; set; }
        public string TermName { get; set; }
        public int TermType { get; set; }
        public string Timing { get; set; }
        public int Duration { get; set; }
        public string ExternalLink { get; set; }
        public int sortOrder { get; set; }
    
        public virtual Template Template { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TemplateDetailSub> TemplateDetailSubs { get; set; }
    }
}
