//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIUWebAPI.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TermDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TermDetail()
        {
            this.Assignments = new HashSet<Assignment>();
            this.Attendances = new HashSet<Attendance>();
            this.AttendanceTotals = new HashSet<AttendanceTotal>();
            this.LectureNotis = new HashSet<LectureNoti>();
            this.ResultReportIssues = new HashSet<ResultReportIssue>();
            this.TimeTableDetails = new HashSet<TimeTableDetail>();
        }
    
        public int ID { get; set; }
        public int TermID { get; set; }
        public int ModuleID { get; set; }
        public bool UpdateBatch { get; set; }
        public bool ShowInProgramPlan { get; set; }
        public int sortOrder { get; set; }
        public bool StudyResource { get; set; }
        public bool Assignment { get; set; }
        public bool Attendence { get; set; }
        public bool Result { get; set; }
        public int LectureID { get; set; }
        public Nullable<System.DateTime> FirstSubmission { get; set; }
        public Nullable<System.DateTime> FirstResult { get; set; }
        public Nullable<System.DateTime> FinalSubmission { get; set; }
        public Nullable<System.DateTime> FinalResult { get; set; }
        public string Remark { get; set; }
        public Nullable<int> DetailCount { get; set; }
        public Nullable<int> StudentCount { get; set; }
        public Nullable<int> AttendentRate { get; set; }
        public Nullable<bool> Tick1 { get; set; }
        public Nullable<int> Pass1 { get; set; }
        public Nullable<System.DateTime> FirstResultIssue { get; set; }
        public Nullable<bool> Tick2 { get; set; }
        public Nullable<int> Pass2 { get; set; }
        public Nullable<int> AccessorID { get; set; }
        public Nullable<System.DateTime> FinalResultIssue { get; set; }
        public Nullable<int> Management { get; set; }
        public Nullable<int> ModifyID { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Assignment> Assignments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attendance> Attendances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttendanceTotal> AttendanceTotals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LectureNoti> LectureNotis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResultReportIssue> ResultReportIssues { get; set; }
        public virtual Term Term { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeTableDetail> TimeTableDetails { get; set; }
        public virtual Module Module { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
    }
}
