//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIUWebAPI.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeTableDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TimeTableDetail()
        {
            this.Attendances = new HashSet<Attendance>();
        }
    
        public int ID { get; set; }
        public int TermID { get; set; }
        public int TermDetailID { get; set; }
        public int TimeSettingID { get; set; }
        public int DayOfWeekID { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> RoomID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attendance> Attendances { get; set; }
        public virtual Room Room { get; set; }
        public virtual TermDetail TermDetail { get; set; }
        public virtual TimeSetting TimeSetting { get; set; }
    }
}
